'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import useMousePosition from '../utils/useMousePosition'

export default function HelloAnimation() {
    const [isHovered, setIsHovered] = useState(false)

    const { x, y } = useMousePosition()
    const size = isHovered ? 400 : 10

    return (
        <section>
            <div
                className="h-full w-full flex flex-col justify-between transition-all text-[25rem] [mask-image:url('../../public/images/hello.svg')] [mask-repeat:no-repeat] text-center"
                onMouseEnter={() => setIsHovered(true)}
                onMouseLeave={() => setIsHovered(false)}
            >
                <div className="flex">
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                    <div className="w-6 h-6 leading-none transition-all hover:text-2xl">
                        ☺︎
                    </div>
                </div>
                {/* <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div>
                <div className="flex justify-between">
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                    <div>☺︎</div>
                </div> */}
            </div>
            {/* <motion.div
                className="[mask-image:url('../../public/images/mask.svg')] [mask-repeat:no-repeat] absolute top-0 left-0 flex-1 w-full h-full transition-transform duration-100 bg-gradient-to-r from-[#4bbd04] to-[#00B8D4] pointer-events-none transition-all"
                animate={{
                    WebkitMaskPosition: `${x - size / 2}px ${y - size / 2}px`,
                    WebkitMaskSize: `${size}px`,
                }}
                transition={{ type: 'tween', ease: 'backOut' }}
            ></motion.div> */}
        </section>
    )
}
